### ISSUE TITLE
Please tell us if you use hitokoto.cn!

### ISSUE THREAD

**Issue by freejishu** [hitokoto-osc/hitokoto_tell#1]
If you use hitokoto.cn's api,please tell us!
We will screen some greet project and show them in our website!
ps:No language limit.

如果你正在使用hitokoto.cn的服务，请在此留言告诉我们一些信息（比如网址等）！
我们会筛选一批不错的项目或者网站，并且将其展示在主站上。
ps:本issue没有语言限制

**Comment by freejishu** [comment]
个人Blog：https://www.freejishu.com/ 页底

**Comment by stars8** [comment]
个人博客：https://www.chujian.xyz/

**Comment by Blues-star** [comment]
个人博客：https://www.yuukiasuna.cc

**Comment by honjun** [comment]
个人博客： https://www.hojun.cn

**Comment by ghost** [comment]
个人博客：https://blog.woc.cool

**Comment by XianD7** [comment]
个人Blog：https://moexian.com/

**Comment by ztlei** [comment]
个人博客：http://gui.lu/

**Comment by MobiusBeta** [comment]
个人起始导航页：https://www.maorx.cn/a/

**Comment by tea9** [comment]
个人博客：https://tea9.xyz/

**Comment by markey92** [comment]
微信小程序《小新语录》

**Comment by markey92** [comment]
微信小程序【小新语录】

**Comment by sy-records** [comment]
个人博客：https://qq52o.me 页底

**Comment by SaucePlum** [comment]
每日一言：https://www.seacto.cn/
希望与hitokoto.cn共同进步
我们都是句子狂😊

**Comment by qdqqd** [comment]
柯艺云 https://www.qdqqd.com

“生死听天命，你也由天定”

**Comment by philipsc** [comment]
微狗论坛：[https://wedog.cc](https://wedog.cc)（欢迎横幅）
微狗论坛致力于为各位站长交流建站心得、共享技术资讯、分享主机优惠信息等。

**Comment by IcyFeather233** [comment]
个人博客blog.icyfeather.cf 页底，实际上wordpress主题 Sakurairo 的用户都在用一言的接口哦

**Comment by steve02081504** [comment]
https://github.com/Taromati2/ghost/commit/c1bd96640a411e6010cc2a2a03b081c6b66d2659
桌宠👻Taromati2 菜单切换时的空白部分填充
一个用户平均每小时请求一次

**Comment by Jerry12228** [comment]
Jerry的mc皮肤站
[https://account.mc.jerry.ink/](https://account.mc.jerry.ink/) 
用户中心右上角

使用自部署的一言api
[https://hitokoto-api.jerry.ink/](https://hitokoto-api.jerry.ink/)

**Comment by oeyoews** [comment]
[neotw](https://neotw.oeyoewl.top/) 页面底部
