### ISSUE TITLE
功能申请

### ISSUE THREAD

**Issue by greenhat616** [hitokoto-osc/hitokoto_tell#2]
该 issue 的目标在于提交你对于一言的任何期待。
我们会认真评估你的想法， 并考虑是否在未来实现。

建议的格式：
```
## 功能

xxx

## 原因

xxx

## 影响

xxx

## 使用示例

xxx
```

**Comment by beilunyang** [comment]
## 功能
希望能增加一个请求参数max，用来控制只返回不超过最大字数的句子

## 原因
字数过多，会影响前端页面布局

**Comment by greenhat616** [comment]
> ## 功能
> 希望能增加一个请求参数max，用来控制只返回不超过最大字数的句子
> 
> ## 原因
> 字数过多，会影响前端页面布局

这个我们已经在计划中了，谢谢建议。可以加入我们的开发者群，开放时（接口变动）会通知。

**Comment by cuiruileo** [comment]
## 功能

希望增加一言的对话版，两个人剪短的对话模式。

## 使用示例

A说：我爱一言

B说：我也爱

**Comment by freejishu** [comment]
> ## 功能
> 希望增加一言的对话版，两个人剪短的对话模式。
> 
> ## 使用示例
> A说：我爱一言
> 
> B说：我也爱

收到了，不错的新想法，但是需要打磨，具体我们评估下

**Comment by Kainichy** [comment]
## 功能
希望在请求参数中添加选择语言的参数。

## 原因
对于我来说，网站的受众可能不太会除了英语之外的外文……
不同的网站可能也会有不同的语言需求。

## 使用示例
`https://v1.hitokoto.cn/?lang=en&lang=zh`
然后返回只中文或英文的句子。

感谢一言团队呀(o^^o)

**Comment by WEsperas** [comment]
## 功能
希望增加返回指定用户提交或者指定出处的句子
## 使用示例
https://v1.hitokoto.cn/?creator_uid=111
https://v1.hitokoto.cn/?from=monster

**Comment by greenhat616** [comment]
> ## 功能
> 希望增加返回指定用户提交或者指定出处的句子
> 
> ## 使用示例
> https://v1.hitokoto.cn/?uuid=111
> https://v1.hitokoto.cn/?from=monster

@WEsperas 指定 uuid 功能目前是已经有的，不过不在语句接口，你可以看看核心接口部分。
指定来源是一个计划中的特性，我们讨论觉得应该在 v2 中加入。

**Comment by WEsperas** [comment]
> > ## 功能
> > 希望增加返回指定用户提交或指定出处的句子
> > ## 使用示例
> > [https://v1.hitokoto.cn/?uuid=111 ](https://v1.hitokoto.cn/?uuid=111)
> > https://v1.hitokoto.cn/?from=monster
> 
> @WEsperas指定uuid功能当前是已经有的，不过没有语句接口，你可以看看核心接口部分。
> 指定来源是一个计划中的特性，我们讨论觉得应该在v2中加入。

谢谢回复，我想写creator_uid来着，但是写成uuid了，看了一下这是两个不同的参数orz

**Comment by greenhat616** [comment]
> > > ## 功能
> > > 希望增加返回指定用户提交或指定出处的句子
> > > ## 使用示例
> > > [https://v1.hitokoto.cn/?uuid=111 ](https://v1.hitokoto.cn/?uuid=111)
> > > https://v1.hitokoto.cn/?from=monster
> > 
> > 
> > @WEsperas指定uuid功能当前是已经有的，不过没有语句接口，你可以看看核心接口部分。
> > 指定来源是一个计划中的特性，我们讨论觉得应该在v2中加入。
> 
> 谢谢回复，我想写creator_uid来着，但是写成uuid了，看了一下这是两个不同的参数orz

这个可能在 v1 以句集的形式出现。v2 会保留原字段实现。
开发进度可能要另行确定，目前我还是比较忙的

**Comment by WEsperas** [comment]
> > > > ## 功能
> > > > 希望增加返回指定用户提交或指定出处的句子
> > > > ## 使用示例
> > > > [https://v1.hitokoto.cn/?uuid=111 ](https://v1.hitokoto.cn/?uuid=111)
> > > > https://v1.hitokoto.cn/?from=monster
> > > 
> > > 
> > > @WEsperas指定uuid功能当前是已经有的，不过没有语句接口，你可以看看核心接口部分。
> > > 指定来源是一个计划中的特性，我们讨论觉得应该在v2中加入。
> > 
> > 
> > 谢谢回复，我想写creator_uid来着，但是写成uuid了，看了一下这是两个不同的参数orz
> 
> 这个可能在 v1 以句集的形式出现。v2 会保留原字段实现。
> 开发进度可能要另行确定，目前我还是比较忙的

好的收到！感谢开发者，辛苦了|•'-'•)و✧

**Comment by chuchu-z** [comment]
## 功能
如果能实现类似下面这样用 curl 请求直接返回内容, 我会非常喜欢的

```bash
curl http://whatthecommit.com/index.txt
```

## 原因
希望在 shell 中引用到你们的句子作为终端启动欢迎语, 这是一个非常棒的想法

**Comment by greenhat616** [comment]
你可以这么使用：
@chuchu-z curl https://v1.hitokoto.cn/?encode=text

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："chuchu-z ***@***.***&gt;;
发送时间：2021年4月29日(星期四) 下午3:19
收件人："freejishu/hitokoto_tell" ***@***.***&gt;;
抄送："Jonson Petard ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [freejishu/hitokoto_tell] 功能申请 (#2)
-----------------------------------

 

 
功能
 
如果能实现类似下面这样用 curl 请求直接返回内容, 我会非常喜欢的
 curl http://whatthecommit.com/index.txt
 
原因
 
希望在 shell 中引用到你们的句子作为终端启动欢迎语, 这是一个非常棒的想法

**Comment by chuchu-z** [comment]
> 你可以这么使用： @chuchu-z curl https://v1.hitokoto.cn/?encode=text
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："chuchu-z ***@***.***&gt;; 发送时间：2021年4月29日(星期四) 下午3:19 收件人："freejishu/hitokoto_tell" ***@***.***&gt;; 抄送："Jonson Petard ***@***.***&gt;;"Author ***@***.***&gt;; 主题：Re: [freejishu/hitokoto_tell] 功能申请 (#2) ----------------------------------- 功能 如果能实现类似下面这样用 curl 请求直接返回内容, 我会非常喜欢的 curl http://whatthecommit.com/index.txt 原因 希望在 shell 中引用到你们的句子作为终端启动欢迎语, 这是一个非常棒的想法 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是的, 我已经确认了是 git bash 终端的 curl 有问题, 感谢你的回复

**Comment by akqaq** [comment]
## 功能
在一言接口介绍处，可以细致写上，日流多少会被限制
## 原因
让我们使用者能够做到心中有数（虽然我这辈子可能都不会被限制到，但是~）
另外，2021年已经过去一半了，**v2接口**什么时候上线呢

**Comment by greenhat616** [comment]
@OnlywithUU 
1、`v1.hitokoto.cn` 使用CDN 限制 QPS  的方法。理论上这个 QPS 的粒度是 5 秒。；
2、很高兴你关注 v2 的开发进度。目前 v2 仍处于讨论实现阶段，我个人在做的工作是逐步模块化，可控化，数据化，容器化现有的组件。受制于项目负责人和建模设计核心开发者事务繁忙，这段时间都没有推进工作。理想状态下今年 Q3 可以发布包含一定新功能的预览版（面板，新 API），这个状态按我们团队目前的状态可能会维持很长的状态。如果您乐意参与开发的话，也可以联系我们。

欢迎加入社群和我们一起吹水哦：
* Telegram: https://t.me/@hitokoto
* QQ: 33542648 （请备注来自 Github 或者 仓库地址）

**Comment by wtyang** [comment]
## 功能

新增“程序员”分类

## 原因

开发接口的都是程序员呢。能看到一言的应该也都是程序员开始的吧

## 影响

有些程序员语录或者是互联网相关的可以放到里面

## 使用示例

代码写得越急，程序跑得越慢。    分类：程序员

**Comment by L-Sun** [comment]
## 功能

添加 请求编码为 svg

## 原因

由于很多Markdown并不支持直接使用 script标签，或者用js脚本请求。

## 影响

可以在 GitHub 的markdown中放入一言，比如GitHub的个人页面 (Profile)

## 使用示例
```html
<img src="https://v1.hitokoto.cn?encode=svg" />
```

**Comment by n0tssss** [comment]
## 功能

过滤一些低质量的一言

## 原因

在选择“动画”这个参数时，会有 “哦！” 等一个词汇的一言，希望可以增加一个过滤，如少于几个字段则不需要

## 影响

太短显得莫名其妙

**Comment by greenhat616** [comment]
@N0ts123 https://developer.hitokoto.cn/sentence/#请求参数

已支持的功能

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："N0ts ***@***.***&gt;;
发送时间：2021年11月22日(星期一) 下午4:34
收件人："freejishu/hitokoto_tell" ***@***.***&gt;;
抄送："Jonson Petard ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [freejishu/hitokoto_tell] 功能申请 (#2)
-----------------------------------

 

 
功能
 
过滤一些低质量的一言
 
原因
 
 在选择“动画”这个参数时，会有 “哦！” 等一个词汇的一言，希望可以增加一个过滤，如少于几个字段则不需要
 
影响
 
太短显得莫名其妙

**Comment by deventw** [comment]
## 功能

希望在請求參數中添加選擇語言轉換的參數。

## 原因

希望請求結果的語錄返回為繁體。

## 影響

不同的網站可能有不同的語言需求。

## 使用示例

`https://v1.hitokoto.cn/?lang=en&lang=zhTW`
`https://v1.hitokoto.cn/?convert=zhTW`
然後返回中文或英文都可以，但如果為中文自動轉換為繁體

感謝一言團隊~

**Comment by greenhat616** [comment]
> ## 功能
> 
> 希望在請求參數中添加選擇語言轉換的參數。
> ## 原因
> 
> 希望請求結果的語錄返回為繁體。
> ## 影響
> 
> 不同的網站可能有不同的語言需求。
> ## 使用示例
> 
> `https://v1.hitokoto.cn/?lang=en&lang=zhTW` `https://v1.hitokoto.cn/?convert=zhTW` 然後返回中文或英文都可以，但如果為中文自動轉換為繁體
> 
> 感謝一言團隊~

前提：目前暂不打算在 `v1` 接口中新增新功能；下一大版中有考虑集成此功能。
注：有必要的话，可以使用下方提供的方法，强转文字。但本人觉得这可能会不符合各地区繁中使用者的使用习惯。

## 需求分析

该功能如果需要兼容 `正體中文（台灣）、正體中文（香港）` 等不同地区的语法习惯的话，显然不能直接转换文字的编码。
* 比如说 头发 的 发，繁体中有 髪 和 發。需要根据不用场景来决定使用何种文字。
* 繁中地区使用的文字也有差异，如：
  * 爲→為
  * 啓→啟
  * 着→著
  * 裏→裡
  * 麪→麵
* 繁中地区词组的使用习惯不同，如：
  * 服务器 -> 伺服器
  * 短信 -> 簡訊
  * 秋千 -> 鞦韆

* 一言中收录的很多作品，繁中都有对应的翻译，哪怕基于词组的一对一翻译，也很可能不能保证原汁原味

## 可能的解决方案

如果在未来实现的话，我们暂时考虑使用自动翻译器，比如说 `OpenCV` 在后端预处理文字转换为不同繁中地区的使用习惯，同时需要审核员确认来改正对应文字。（此处需要斟酌）

## 临时的即时转码方案

注： 本节引入的方法都是变化的是字形，我们考虑到不同地区的使用习惯的差异，因此线上不打算上线本节的方案。您可以参考一下。

* 直接 JS 转换字形：https://laowangblog.com/simplified-traditional-conversion-js.html
* 利用 CSS 进行转换：https://ave-maria.gitee.io/banomo/vue_zh_tw_2.html
  * 这种方法需要系统的字体包含繁中变体，一般来说 Windows 不符合需求

**Comment by edocli** [comment]
## 功能

能够返回一个一言卡片

## 原因

增加功能，提高实用性和美观

**Comment by greenhat616** [comment]
> ## 功能
> 能够返回一个一言卡片
> 
> ## 原因
> 增加功能，提高实用性和美观

计划中...

**Comment by Nododo** [comment]
## 功能

能够增加古诗词按年级分类功能
从小学到高中，每个年级应该掌握哪些古诗

## 原因

失业iOS开发想做一个具有此功能的APP

**Comment by greenhat616** [comment]
> ## 功能
> 能够增加古诗词按年级分类功能 从小学到高中，每个年级应该掌握哪些古诗
> 
> ## 原因
> 失业iOS开发想做一个具有此功能的APP

**先下结论：此需求已离题，我们暂不考虑将此功能加入 v1、v2 接口中提供一方支持。**

不过我们可以为你的需求进行分析：

这个主要的问题在于是否判断每个年级需要掌握哪些故事——这个是信息，核心在于缺乏信息源。

**很遗憾，我们也没有相关的信息。**

当你有了以上信息源，利用爬虫可以很轻易得把各个古诗拉取下来。此时你需要做的，只需要内嵌这个数据到你的本地 APP，亦或者直接做成接口。

**Comment by Nododo** [comment]
> 

OK 

感谢回答

**Comment by sunviv** [comment]
## 功能
希望增加去除标点符号并按段落拆分成数组的功能

## 原因
在文字竖排并有换行的情况下，标点符号显示影响美观也不合理

**Comment by greenhat616** [comment]
> ## 功能
> 
> 希望增加去除标点符号并按段落拆分成数组的功能
> ## 原因
> 
> 在文字竖排并有换行的情况下，标点符号显示影响美观也不合理

可以在用户端实现的。
