### ISSUE TITLE
在QQ/微信上发送一言

### ISSUE THREAD

**Issue by Nothing0011desu** [hitokoto-osc/hitokoto_tell#6]
希望可以有对于QQ机器人/微信公告的一言
原因是因为在许多oj上看到过一言，有了在QQ或者微信可以类似于telegram的bot自动推送的想法
实例：
                                        ＜6:00＞
                                                       #一言内容   ＜头像＞

**Comment by freejishu** [comment]
QQ群组机器人现在我们运营了，目前有频道机器人（使用腾讯官方接口&审核上架），名叫”小言同学“，可搜索添加或前往频道寻找帮助。
微信机器人暂无计划，但是Api接口已经提供，可以给各位dalao手动DIY的机会 ：）
